# Generated by Django 3.1.7 on 2021-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20210221_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='receipt',
            field=models.ImageField(default='Desert 3.jpg', upload_to='../static/images'),
        ),
    ]
